
name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

# Note: To build mobile apps (.apk and .ipa), you would need to set up a more complex
# workflow with Android SDK and iOS build environments.
# This would typically involve:
# 1. Setting up Capacitor
# 2. Building the web app
# 3. Syncing with Capacitor
# 4. Building for Android (requires Android SDK)
# 5. Building for iOS (requires macOS runner with Xcode)

